paths:
 /api/products/:
  get:
   summary: Obtener todos los productos
   tags:
    - Productos
   responses:
    "200":
     description: Todos los productos fueron obtenidos correctamente.
     content:
      application/json:
       schema:
        type: array
        items:
         $ref: '#components/schemas/Product'
    "401":
     description: Error por falta de permisos.
    "500":
     description: Error interno del servidor.
  post:
   summary: Crear producto.
   tags:
    - Productos
   requestBody:
    required: true
    content: 
     application/json:
      schema:
       $ref: "#components/requesBodies/UpdateProduct"
   responses: 
    "200":
     description: El producto se creó correctamente.
     content:
      application/json:
       schema:
        type: object
        properties:
         status:
          type: string
         payload:
          $ref: "#components/schemas/Product"
    "500":
     description: Error interno del servidor.
 /api/products/{pid}:
  get:
   summary: Obtener un producto específico
   tags:
    - Productos
   parameters:
    - name: pid
      in: path
      required: true
      description: pid es el id del producto que desea obtener
      schema:
       type: string
   responses:
    "200":
     description: El producto se obtuvo corrrectamente
     content: 
      application/json:
       schema:
        $ref: '#components/schemas/Products'
    "500":
     description: Error interno del servidor. 
  put:
   summary: Modificar productos.
   tags:
    - Productos
   parameters:
     - name: pid
       in: path
       required: true
       description: pid es el id del producto que desea obtener
       schema:
        type: string    
   requestBody:
    required: true
    content: 
     application/json:
      schema:
       $ref: "#components/requestBodies/UpdateProduct"
   responses: 
    "200":
     description: El producto se modificó correctamente.
     content:
      application/json:
       schema:
        type: object
        properties:
         status:
          type: string
         payload:
          $ref: "#components/schemas/Product"
    "500":
     description: Error interno del servidor.
  delete:
   summary: Eliminar productos.
   tags: 
    - Productos
   parameters:
     - name: pid
       in: path
       required: true
       description: pid es el id del producto que desea obtener
       schema:
        type: string
   responses:
        "200":
         description: Se elimino el usuario correctamente
        "500":
         description: Error interno del servidor
             
components:
 schemas:
  Product:
   type: object
   properties: 
    _id:
     type: ObjectId
     description: Id del producto
    title:
     type: string
     description: Titulo del producto
    description:
     type: string
     description: Descripción del producto.
    price:
     type: number
     description: Precio del producto.
    stock: 
     type: number
     description: Stock del producto.
    category:
     type: string
     description: Categoria del producto
    owner:
     type: ObjectId
     description: Id del propietario.
   example: 
    _id: ObjectId("gsa98273skjhgda8912")
    title: Camiseta de futbol
    description: Camiseta de Argentina titular
    price: 26.000
    stock: 22
    category: Camisetas
    owner: ObjectId("gsa98273skjhgda8912")
 requestBodies:
  UpdateProduct:
   type: object
   properties:
    title:
     type: string
     description: Titulo del producto
    description:
     type: string
     description: Descripción del producto.
    price:
     type: number
     description: Precio del producto.
    stock: 
     type: number
     description: Stock del producto.
    category:
     type: string
     description: Categoria del producto
   example:
    title: Camiseta de futbol
    description: Camiseta de Argentina titular
    price: 26.000
    stock: 22
    category: Camisetas
    